######################################################################
# Author: Hilal Coşgun
# ID: 22201571
# Section: 1
# Homework: 3
# Description: Makefile
######################################################################

build:
	g++ substrings.cpp -o substrings
	g++ minimalset.cpp -o minimalset
	g++ lexicographic.cpp -o lexicographic
	g++ insertionorders.cpp -o insertionorders
	