######################################################################
# Author: Hilal Coşgun
# ID: 22201571
# Section: 1
# Homework: 2
# Description: Makefile
######################################################################

build:
	g++ least5.cpp Heap.h Heap.cpp  -o least5
	g++ game.cpp AVLTree.h AVLTree.cpp  -o game
	g++ prefixsubarrays.cpp AVLTree.h AVLTree.cpp -o prefixsubarray
	g++ subarrays.cpp AVLTree.h AVLTree.cpp -o subarray
	